export const GET_AUTH = 'GET_AUTH';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const LOADING_AUTH = 'LOADING_AUTH';
export const GET_ERRORS = 'GET_ERRORS';

//JobDay
export const GET_MONTH = 'GET_MONTH';
export const LOADING_MONTH = 'LOADING_MONTH';
export const CREATE_JOBDAY_CHECKIN_AUTOMATIC =
  'CREATE_JOBDAY_CHECKIN_AUTOMATIC';
export const CREATE_JOBDAY_CHECKOUT_AUTOMATIC =
  'CREATE_JOBDAY_CHECKOUT_AUTOMATIC';
