export const GET_AUTH = 'GET_AUTH';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const LOADING_AUTH = 'LOADING_AUTH';
export const GET_ERRORS = 'GET_ERRORS';
//Messages
export const GET_MESSAGES = 'GET_MESSAGES';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const MESSAGE_LOADING_START = 'MESSAGE_LOADING_START';
export const MESSAGE_LOADING_END = 'MESSAGE_LOADING_END';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//JobDay
export const GET_JOBDAYS = 'GET_JOBDAYS';
export const GET_SELECTED_DAY = 'GET_SELECTED_DAY';
export const LOADING_JOBDAYS = 'LOADING_JOBDAYS';

export const GET_CURRENT_START = 'GET_CURRENT_START';
export const GET_CURRENT_END = 'GET_CURRENT_END';
export const GET_CURRENT_TIME = 'GET_CURRENT_TIME';

export const SET_ENDTIME_MANUALLY = 'SET_ENDTIME_MANUALLY';

//Get Project
export const GET_PROJECT = 'GET_PROJECT';
//Location
export const GET_LOCATION_MATCH = 'GET_LOCATION_MATCH';
